import React from 'react';
import { Bot, Sparkles } from 'lucide-react';
import { ACTION_LABEL } from '../../lib/labels';
import { Spinner } from '../ui/Spinner';

export function AiSummaryCard({ decision, loading = false, className = '' }) {
  if (loading) {
    return (
      <div className={`card ${className}`}>
        <Spinner label="Generating AI explanation..." size={24} />
      </div>
    );
  }

  if (!decision || decision.ai_summary_status === 'not_generated') {
    return null;
  }

  const actionText = ACTION_LABEL[decision.ai_suggested_action] || decision.ai_suggested_action;

  return (
    <div
      className={`card ${className}`}
      style={{
        background: 'linear-gradient(135deg, #FFFFFF 0%, #F4F7FB 100%)',
        borderLeft: '4px solid var(--color-primary)',
      }}
    >
      <div className="card-title" style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}>
        <Sparkles size={18} style={{ color: 'var(--color-primary)' }} />
        <span>AI explanation — does not decide</span>
        {decision.ai_suggested_action && (
          <span
            style={{
              marginLeft: 'auto',
              fontSize: 'var(--fs-xs)',
              padding: '2px 8px',
              borderRadius: 12,
              backgroundColor: 'var(--color-primary-soft)',
              color: 'var(--color-primary)',
              fontWeight: 600,
            }}
          >
            Suggested: {actionText}
          </span>
        )}
      </div>

      <p style={{ fontSize: 'var(--fs-sm)', lineHeight: 1.6, color: 'var(--color-text)' }}>
        {decision.ai_summary || 'No AI summary available.'}
      </p>

      <div
        style={{
          marginTop: 'var(--space-3)',
          fontSize: '11px',
          color: 'var(--color-text-muted)',
          display: 'flex',
          alignItems: 'center',
          gap: 4,
        }}
      >
        <Bot size={12} />
        <span>Generated by LLM assistant strictly from verified database records.</span>
      </div>
    </div>
  );
}
